import './globals.css'

import type { Metadata } from 'next'
import { Inter, MonteCarlo, Playfair_Display } from 'next/font/google'
import { env } from '~/env'
import { QueryProvider } from '~/providers/query-client'

// Validate environment variables on app start
env

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
})

const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-serif',
})

const monteCarlo = MonteCarlo({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-script',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className={`${inter.variable} ${playfair.variable} ${monteCarlo.variable}`} lang="pt">
      <body className="min-w-80 font-sans">
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  )
}
